FROM python:3.10

WORKDIR /app
ARG TARGET_BRANCH
ARG IMAGE_RECOGNITION_MODEL
ENV DEPLOYMENT=local

SHELL ["/bin/bash", "-c"]

RRUN apt-get update \
&& apt-get -y install git unzip \
&& curl -LsSf https://astral.sh/uv/install.sh | sh \
&& source ${HOME}/.local/bin/env \
&& git clone https://github.com/toposoid/toposoid-common-image-recognition-web.git \
&& cd toposoid-common-image-recognition-web \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& sed s/__##GIT_BRANCH##__/${TARGET_BRANCH}/g pyproject.toml.template > pyproject.toml \
&& uv sync \
&& uv add git+https://github.com/toposoid/toposoid-python-lib.git@${TARGET_BRANCH}#egg=ToposoidCommon \
&& uv run downloadModel-${IMAGE_RECOGNITION_MODEL}.py


