version: '3'
services:
  toposoid-common-image-recognition-web:
    image: toposoid-common-image-recognition-web:0.5-SNAPSHOT
    tty: true
    environment:
      - TOPOSOID_IMAGE_RECOGNITION_VIT_MODEL=google/vit-base-patch16-224
      - TOPOSOID_IMAGE_RECOGNITION_MOBILE_VIT_MODEL=apple/mobilevit-small
      - TOPOSOID_IMAGE_RECOGNITION_MOBILE_VIT_USE=0
    ports:
      - 9013:9013
