version: '3.4'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
services:
  toposoid-common-image-recognition-web:
    image: toposoid/toposoid-common-image-recognition-web:0.5-SNAPSHOT
    environment:
      - TOPOSOID_IMAGE_RECOGNITION_MODEL=google/vit-base-patch16-224
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9013:9013

    