version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-common-image-recognition-web:
    image: toposoid/toposoid-common-image-recognition-web:0.5-SNAPSHOT
    tty: true
    environment:
      - TOPOSOID_IMAGE_RECOGNITION_VIT_MODEL=google/vit-base-patch16-224
      - TOPOSOID_IMAGE_RECOGNITION_MOBILE_VIT_MODEL=apple/mobilevit-small
      - TOPOSOID_IMAGE_RECOGNITION_MOBILE_VIT_USE=1
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9013:9013
